#!/bin/bash

emcc lame-svn/lame/libmp3lame/.libs/libmp3lame.a -o liblame.js -s EXPORTED_FUNCTIONS="['_hip_decode_init','_hip_decode','_hip_decode1','_hip_decode1_headers','_lame_init', '_lame_close', '_lame_set_in_samplerate','_lame_set_VBR', '_lame_init_params','_lame_set_disable_reservoir','_lame_set_brate','_lame_set_mode','_lame_encode_buffer']" -s EXTRA_EXPORTED_RUNTIME_METHODS="['writeAsciiToMemory', 'ccall', 'setValue', 'getValue', 'cwrap']" --memory-init-file 0 --post-js lame.post.js -Os

cat > liblame.min.js <<ø
(function () {
  if (typeof define !== "function") {
    var define = function (f) {
      var ret = f();
      var k;
      for(k in ret) {
        window[k] = ret[k];
      }
    };
  }

  define(function() {
ø

cat liblame.js >> liblame.min.js 

cat >> liblame.min.js <<ø
    return { Mp3Encoder: Mp3Encoder, Mp3Decoder: Mp3Decoder };
  });

})();
ø
